[package]
name = "linker-daemon"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "linkerd"
path = "src/main.rs"

[dependencies]
clap.workspace = true
fs2.workspace = true
notify.workspace = true
linker-core = { path = "../linker-core" }

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
